import type { ScenarioPreset } from "../../types";

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: "relocation-household",
    title: "Relocation",
    subtitle: "Home, work, and daily life",
    description: "Compare candidate home areas against household anchors and daily-life needs.",
    category: "relocation",
    featured: true,
    settings: {
      selectedScenario: "relocation-household",
      hasCompletedFirstRun: true,
      mobilityMode: "walk",
      transportMode: "foot-walking",
      routingProvider: "ors",
      isochroneMode: "overlap",
      preset: "balanced",
      timeMinutes: 20,
      timeBuckets: [5, 10, 15, 20],
      ringSpacingMinutes: 5,
      opacity: 0.32,
      labelDensity: "medium",
      layoutMode: "map-first",
    },
  },
  {
    id: "dual-career",
    title: "Dual Career",
    subtitle: "Two commutes, one home base",
    description: "Find overlap areas that keep two work anchors within practical travel time.",
    category: "relocation",
    settings: {
      selectedScenario: "dual-career",
      hasCompletedFirstRun: true,
      mobilityMode: "bike",
      transportMode: "driving-car",
      routingProvider: "ors",
      isochroneMode: "overlap",
      preset: "balanced",
      timeMinutes: 30,
      timeBuckets: [10, 15, 20, 25, 30],
      ringSpacingMinutes: 5,
      opacity: 0.34,
      labelDensity: "medium",
      layoutMode: "split",
    },
  },
  {
    id: "hospital-on-call",
    title: "On-Call Care",
    subtitle: "Hospital reach threshold",
    description: "Constrain candidate areas by hospital access before comparing daily-life fit.",
    category: "relocation",
    settings: {
      selectedScenario: "hospital-on-call",
      hasCompletedFirstRun: true,
      mobilityMode: "walk",
      transportMode: "driving-car",
      routingProvider: "ors",
      isochroneMode: "individual",
      preset: "compact",
      timeMinutes: 20,
      timeBuckets: [5, 10, 15, 20],
      ringSpacingMinutes: 5,
      opacity: 0.3,
      labelDensity: "medium",
      layoutMode: "map-first",
    },
  },
  {
    id: "school-fit",
    title: "School Fit",
    subtitle: "Schools plus routines",
    description: "Compare school access alongside commute, family, and daily-life anchors.",
    category: "relocation",
    settings: {
      selectedScenario: "school-fit",
      hasCompletedFirstRun: true,
      mobilityMode: "stroller",
      transportMode: "foot-walking",
      routingProvider: "ors",
      isochroneMode: "individual",
      preset: "compact",
      timeMinutes: 15,
      timeBuckets: [5, 10, 15],
      ringSpacingMinutes: 5,
      opacity: 0.3,
      labelDensity: "low",
      layoutMode: "map-first",
    },
  },
  {
    id: "workforce-access",
    title: "Workforce",
    subtitle: "Jobs, training, and services",
    description: "Compare access between job centers, training sites, transit, and support services.",
    category: "civic",
    settings: {
      selectedScenario: "workforce-access",
      hasCompletedFirstRun: true,
      mobilityMode: "walk",
      transportMode: "foot-walking",
      routingProvider: "ors",
      isochroneMode: "overlap",
      preset: "spacious",
      timeMinutes: 30,
      timeBuckets: [10, 15, 20, 25, 30],
      ringSpacingMinutes: 5,
      opacity: 0.34,
      labelDensity: "high",
      layoutMode: "split",
    },
  },
  {
    id: "asset-audit",
    title: "Asset Audit",
    subtitle: "Existing capacity before grants",
    description: "Map current public assets, service reach, duplication risk, and remaining gaps.",
    category: "civic",
    featured: true,
    settings: {
      selectedScenario: "asset-audit",
      hasCompletedFirstRun: true,
      mobilityMode: "walk",
      transportMode: "foot-walking",
      routingProvider: "ors",
      isochroneMode: "overlap",
      preset: "spacious",
      timeMinutes: 30,
      timeBuckets: [5, 10, 15, 20, 25, 30],
      ringSpacingMinutes: 5,
      opacity: 0.36,
      labelDensity: "high",
      layoutMode: "split",
    },
  },
  {
    id: "laundromat-walkability",
    title: "Laundromats",
    subtitle: "10-minute daily need test",
    description: "Show which households fall outside a practical walk to a basic daily-life amenity.",
    category: "civic",
    featured: true,
    settings: {
      selectedScenario: "laundromat-walkability",
      hasCompletedFirstRun: true,
      mobilityMode: "walk",
      transportMode: "foot-walking",
      routingProvider: "ors",
      isochroneMode: "individual",
      preset: "compact",
      timeMinutes: 10,
      timeBuckets: [5, 10],
      ringSpacingMinutes: 5,
      opacity: 0.3,
      labelDensity: "medium",
      layoutMode: "map-first",
    },
  },
  {
    id: "real-estate-dev",
    title: "Real Estate Dev",
    subtitle: "Site reach and overlap",
    description: "Compare drive, bike, and walk access across candidate sites.",
    category: "development",
    settings: {
      selectedScenario: "real-estate-dev",
      hasCompletedFirstRun: true,
      mobilityMode: "bike",
      transportMode: "cycling-regular",
      routingProvider: "ors",
      isochroneMode: "overlap",
      preset: "balanced",
      timeMinutes: 20,
      timeBuckets: [5, 10, 15, 20, 25, 30],
      ringSpacingMinutes: 5,
      opacity: 0.32,
      labelDensity: "medium",
      layoutMode: "split",
    },
  },
  {
    id: "home-seeker",
    title: "Home Seeker",
    subtitle: "Daily-life accessibility",
    description: "Find nearby places that are practical for walking, strollers, or slower pace.",
    category: "relocation",
    settings: {
      selectedScenario: "home-seeker",
      hasCompletedFirstRun: true,
      mobilityMode: "stroller",
      transportMode: "foot-walking",
      routingProvider: "ors",
      isochroneMode: "individual",
      preset: "compact",
      timeMinutes: 15,
      timeBuckets: [5, 10, 15],
      ringSpacingMinutes: 5,
      opacity: 0.3,
      labelDensity: "low",
      layoutMode: "map-first",
    },
  },
  {
    id: "urban-planner",
    title: "Urban Planner",
    subtitle: "Coverage and equity gaps",
    description: "Analyze walking and biking coverage where hills change real access.",
    category: "civic",
    settings: {
      selectedScenario: "urban-planner",
      hasCompletedFirstRun: true,
      mobilityMode: "walk",
      transportMode: "foot-walking",
      routingProvider: "ors",
      isochroneMode: "overlap",
      preset: "spacious",
      timeMinutes: 30,
      timeBuckets: [5, 10, 15, 20, 25, 30],
      ringSpacingMinutes: 5,
      opacity: 0.36,
      labelDensity: "high",
      layoutMode: "split",
    },
  },
];

export function getScenarioPreset(id: ScenarioPreset["id"]) {
  return SCENARIO_PRESETS.find((scenario) => scenario.id === id);
}
